const data3 = [
    [
        {id:1,Name:"EMP_ID" ,Type:"Numeric",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:2,Name:"EMP_FNAME" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:3,Name:"EMP_MI" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:4,Name:"EMP_LNAME" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:5,Name:"DOJ" ,Type:"Data",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:6,Name:"DOB" ,Type:"Data",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:5,Name:"EMP_CAT" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:8,Name:"EMP_DEP" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:9,Name:"EMP_STATUS" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:""},
        {id:10,Name:"EMP_TITLE" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        
    ],
    [
        {Name:"EMP_ID" ,Type:"Numeric",Business_Name:"",Business_Description:""},
        {Name:"EMP_FNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_MI" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_LNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"DOJ" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"DOB" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"EMP_CAT" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_DEP" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_STATUS" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_TITLE" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        
    ],
    [
        {Name:"EMP_ID" ,Type:"Numeric",Business_Name:"",Business_Description:""},
        {Name:"EMP_FNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_MI" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_LNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"DOJ" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"DOB" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"EMP_CAT" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_DEP" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_STATUS" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_TITLE" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        
    ],
    [
        {Name:"EMP_ID" ,Type:"Numeric",Business_Name:"",Business_Description:""},
        {Name:"EMP_FNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_MI" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_LNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"DOJ" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"DOB" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"EMP_CAT" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_DEP" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_STATUS" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_TITLE" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        
    ],
    [
        {Name:"EMP_ID" ,Type:"Numeric",Business_Name:"",Business_Description:""},
        {Name:"EMP_FNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_MI" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_LNAME" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"DOJ" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"DOB" ,Type:"Data",Business_Name:"",Business_Description:""},
        {Name:"EMP_CAT" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_DEP" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_STATUS" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        {Name:"EMP_TITLE" ,Type:"Varchar",Business_Name:"",Business_Description:""},
        
    ],
    [
        {Name:"EMP_ID" ,Type:"Numeric",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"EMP_FNAME" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"EMP_MI" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"EMP_LNAME" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"DOJ" ,Type:"Data",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"DOB" ,Type:"Data",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"EMP_CAT" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"EMP_DEP" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"EMP_STATUS" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        {Name:"EMP_TITLE" ,Type:"Varchar",Business_Name:"asdfkfnjdfn",Business_Description:"asdfkfnjdfn"},
        
    ],
]
export default data3;